[build]
builder = "NIXPACKS"
buildCommand = "cd backend && npm install && npx prisma generate && npx prisma db push"

[deploy]
startCommand = "cd backend && node prisma/seed.js && node src/app.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 120
